### ISSUE TITLE
Videos explaining IPLD

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipld/ipld#10]
For the next version of the website, it would be good if we have some concise videos talking about what IPLD is and how it works.

Ref: https://github.com/ipld/website/issues/17

**Comment by diasdavid** [comment]
Videos on the website! <img width="1150" alt="image" src="https://user-images.githubusercontent.com/1211152/37694434-6869adf4-2c84-11e8-8363-0fac937829eb.png"> :)
