### ISSUE TITLE
Updating media section on front page

### ISSUE THREAD

**Issue by vmx** [ipld/ipld#108]
The old IPLD front page is back, but only one video has been updated. Currently 5 videos are linked, I suggest making the "Foundations for Decentralization: Data with IPLD" one (which is already part of the media section in the docs), one of those five videos.

**Comment by rvagg** [comment]
Specifically this video is being suggested: https://ipld.io/media/#foundations-for-decentralization-data-with-ipld--gpn19

Probably remove one of those two on the bottom.

@RangerMauve are you interested in picking this one off?

**Comment by RangerMauve** [comment]
Just to confirm, this is issue is for linking the media on the home page to individual sections in the `/media` page?

Or is it to update the media that is being linked to?

**Comment by rvagg** [comment]
on the main, "splash", page

Backstory here is that the original ipld/ipld launch entirely replaced ipld.io, but then objections were raised to the loss of the original shiny main page, so it was shoehorned back in as a "splash" but is basically unmodified from what it was originally.

So now we have the situation where we have 4 videos on the splash that are _really_ old (we replaced the main one with the newer resnetlab on-tour video) but we also have this "media" section that has more recent and relevant videos.

So the ask here is to just take a look at those 4 videos an consider what we could do to update them with content that is more relevant to current IPLD philosophy and code. The one GPN19 one is particularly good and deep content from Eric and would be good in there.

I'd be interested to hear your opinions on what content might be good to lead with on that splash.

**Comment by RangerMauve** [comment]
Looking at the splash vs the media page:

- [IPFS Blockchain Fun](https://www.youtube.com/watch?v=bi-4YGZXxwA) seems a bit out dated and more focused on IPFS, I think that would be a good candidate for replacing with Eric's GPN19 talk
- [Juan Benet: Enter the Merkle Forest](http://localhost:8080/media/#foundations-for-decentralization-data-with-ipld--gpn19) seems good, but maybe we could reorder it to go after Eric's thing
- The ResNetLab video is good as the initial splash, IMO
- [Why Must we Distribute The Web](https://www.youtube.com/watch?v=skMTdSEaCtA) is good, it's not exactly up to date, but I think the context for it is still relevant for folks that might be seeing IPLD before IPFS.
- [Interplanetary OS](https://www.youtube.com/watch?v=Pjyo2uILcOs) has a bit of IPLD stuff in there, but it's already covered by other videos and it feels a bit further removed. Might be good to replace this with another video, but I'm not sure which one.


After searching Youtube, this video that talks about IPLD and Filecoin. Might be a good replacement for the Interplanetary OS vidoe?

**Comment by rvagg** [comment]
Yes, https://www.youtube.com/watch?v=AWMMnenHQJM is good, but it's the same slide content as the ResNetLab On-Tour one (I was supposed to deliver that talk but I think TZ problems got in the way and Dan stepped in and just delivered the same slides that I'd built for ResNetLab). So best not double-up content.

There's this really rough tutorial walk-through I did with Lindsay a couple of months ago: https://github.com/protocol/launchpad/tree/gitbook/docs/ipld#tutorials, probably not ideal for front-page and I expect Lindsay (or someone) to do a more profesh version at some stage.

Browsing through https://github.com/protocol/launchpad/blob/gitbook/docs/ipld/ipld-resources.md, there's also https://www.youtube.com/watch?v=Y_-TWTmF_1I which _may_ be interesting, it's pretty IPFS / files focused. But I think it's a good explainer that gets into DAGs IIRC.
