### ISSUE TITLE
add pointers to js libraries

### ISSUE THREAD

**Issue by warpfork** [ipld/ipld#140]
It would be super nice to have some links pointing to which source repos, docs sites, npm packages, etc, a new developer should check out first for javascript.

The place for this is the [libraries/javascript](https://github.com/ipld/ipld/tree/master/libraries/javascript) directory.

There may be more than one answer, and that's fine.

This doesn't need to go in depth (and probably _shouldn't_ contain a ton of code samples -- it should link out to somewhere that has those code samples and also knows how to run them so they don't go stale!).  Just pointers to the right repos to look at is enough.

**Comment by rvagg** [comment]
Brenda, Marina and I are planning on doing this collaboratively next week. Matthew has put up his hand for https://github.com/multiformats/js-multiformats/issues/47 which is where we're primarily going to link to, so we should be golden.

**Comment by warpfork** [comment]
If you want to beta test the [ipld compliance checklist (draft)](https://www.notion.so/protocollabs/2021-11-ipld-compliance-checklist-ebd7e12edda84e72a895e66533e11ca2), it might also produce interesting results?  (What it produces might be longish, though, and we should also still have just brief links.  And I don't know if it'll be that useful of a lens for comparing the different JS implementations out there right now, since I think (iiuc) that those mostly differ in JS API conventions rather than IPLD feature support levels or semantics.)
