### ISSUE TITLE
dag-json slash escaping

### ISSUE THREAD

**Issue by tysonzero** [ipld/ipld#148]
It seems like making dag-json truly support the full IPLD Data Model would not be particularly onerous.

One possibility is mapping `"/"` map keys in the data-model to `"//"`, `"//"` to `"///"` and so on.

Whilst this is potentially breaking, the situations in which it will break are situations that are playing with fire as is, by having keys very similar to the disallowed `"/"`.

**Comment by rvagg** [comment]
ooof, it looks like the latest edits to the spec didn't make it in migration to this repo, but we do cover in detail some of the reserved space (`"/"`) rules @ https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-json.md#the-reserved-namespace

These rules narrow down the range of unsupported data a little so it's not just that `"/"` isn't a supported key. The maps that use that as a reserved key are single-key maps, so >1 key shouldn't get caught in the trap (although I can't recall if our main implementations do this properly or not!).

But yes, you're right, we could introduce escaping and have discussed doing this. I don't recall why we didn't but it might have just been the additional complexity for a codec that we don't expect to have as wide ("serious") use as dag-cbor. But that could be a bad reason to not pursue it!
