### ISSUE TITLE
"dag-" prefix in codec names

### ISSUE THREAD

**Issue by vmx** [ipld/ipld#157]
I stumbled upon the documentation and found that we have a specification for the [dag-eth codec](https://github.com/ipld/ipld/tree/a5631eeadd3b2fe71fd7d6526231a412ffc84fff/specs/codecs/dag-eth). I wondered why it has the "dag-" prefix?

As there isn't any documentation and probably no shared agreement on what the "dag-" prefix means for a codec, I'd like to discuss it here. Perhaps we find agreement, which will make naming things in the future also easier (as I've seen discussion about other "dag-" codecs, where it didn't make sense to me).

I see the "dag-" prefix being used for codecs, where the original format doesn't have any notion of a hash link. We then define a way on how to represent a hash link, so that that codec can be used to describe DAGs. Such a codec that has the "dag-" prefix.

This would explain why we have dag-cbor, dag-json and dag-pb. And also why it is bitcoin and git-raw (I'm a bit confused why it is git-raw and not simply git, but that predates my involvement), which are already codecs that support hash links, hence we don't need to have a special "dag" version of them.

**Comment by rvagg** [comment]
Going to have a say here and then close it but that doesn't mean the discussion has ended - feel free to continue it.

I've been trying to gently discourage the use of `dag` prefixes to new codec names, but people seem to want it. "dageth" and now "dag-ucan" are two new ones.

I think the best way to fix it is to have alternative codecs listed that don't have that prefix, then we muddy the waters enough that people don't do pattern matching. I'm still trying to get to listing the bitcoin codec there too.
