### ISSUE TITLE
No longer missing DAG-JSON fixtures

### ISSUE THREAD

**Issue by vmx** [ipld/ipld#159]
The page at https://ipld.io/specs/codecs/dag-json/ states:

> Fixtures: Fixtures for this system are currently lacking. If you know of some and can link them here, please send an issue or PR.

We now have DAG-JSON fixtures. I'm sure someone who is deeper into the doc system can link things up properly.

**Comment by BigLep** [comment]
https://github.com/ipld/ipld/issues/160 is going to be the master issue for this and related work.

**Comment by rvagg** [comment]
turns out this was done a while back, so closable now without action
