### ISSUE TITLE
DAG-JSON spec isn't the most recent version

### ISSUE THREAD

**Issue by vmx** [ipld/ipld#160]
It looks like something went wrong when merging the specs repo into this repo.

The DAG-JSON specification at https://ipld.io/specs/codecs/dag-json/spec/ isn't the most recent of the spec. The specification at https://github.com/ipld/specs/blob/2a106a9c22a570f436f92ca8aa3de85eb675e116/block-layer/codecs/dag-json.md contains more information and also contains the change that the base64 encoded binary bytes do *not* contain the Multibase prefix.

**Comment by rvagg** [comment]
Going to take care of this soon, will also roll up closing out:

* https://github.com/ipld/ipld/issues/159
* https://github.com/ipld/ipld/issues/148

**Comment by rvagg** [comment]
https://github.com/ipld/ipld/pull/212
