### ISSUE TITLE
enable google analytics tracking

### ISSUE THREAD

**Issue by dharmapunk82** [ipld/ipld#178]
add to site header:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96910779-9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96910779-9');
</script>

**Comment by willscott** [comment]
This needs strong justification if it's going to happen
