### ISSUE TITLE
Provide instructions for how to load IPLD content onto IPFS

### ISSUE THREAD

**Issue by flyingzumwalt** [ipld/ipld#19]
_Note: this is based on the spec in https://github.com/ipld/specs/tree/master/ipld_

Provide instructions (which I think already exist somewhere) showing how to do the following _(ideally from the command line)_

Given IPLD json like:
```
{"article1": {
     “author”:  {"/": “/ipfs/QmYLXcLBTmUJdyocyiRBJT235Wot7AAfYgu974YqCQXUgb”},
     “publisher”:  {"/":  “/ipfs/QmRhVkWJo2vqn6AhdP3JBLsJow8aM7nS9RnUavgojspXXT"}
  }
}
```
I want to resolve hash-referenced content using paths like `/ipld/Qm.../article1/publisher`

## Completion State

These instructions should answer:
1. How do I add the info to IPFS so that it _can_ be resolved as IPLD
2. How do I use IPFS/IPLD to resolve the links?

**Comment by jonnycrunch** [comment]
@nicola @flyingzumwalt any update to how to do this?

**Comment by VictorBjelkholm** [comment]
@jonnycrunch I guess it depends on what exactly you're trying to achieve. We do have the DAG API in both go-ipfs and js-ipfs today. Example made with go-ipfs:

```shell
# Create a new DAG
$ echo '{"username": "victor"}' | ipfs dag put
zdpuB3HcG3VspeH3rJmv4qnFFpD2gfdA3DU8DHLPFwSZEXRVL                                                                                                                             

# Get that newly created DAG
$ ipfs dag get zdpuB3HcG3VspeH3rJmv4qnFFpD2gfdA3DU8DHLPFwSZEXRVL
{"username":"victor"}

# Create a new DAG, linking our previous one in a `friends` array
$ echo '{"username": "joe", "friends": [{"/": "zdpuB3HcG3VspeH3rJmv4qnFFpD2gfdA3DU8DHLPFwSZEXRVL"}]}' | ipfs dag put
zdpuArZXuXxGBKzsbf9CeMvjpV5ScG1oxwvpmcm7vjZK6JDWB                                                                                                                               

# Getting the full DAG
$ ipfs dag get zdpuArZXuXxGBKzsbf9CeMvjpV5ScG1oxwvpmcm7vjZK6JDWB
{"friends":[{"/":"zdpuB3HcG3VspeH3rJmv4qnFFpD2gfdA3DU8DHLPFwSZEXRVL"}],"username":"joe"}

# Looking at just the first friend
$ ipfs dag get zdpuArZXuXxGBKzsbf9CeMvjpV5ScG1oxwvpmcm7vjZK6JDWB/friends/0/
{"username":"victor"}

# Looking specifically at the username of the first friend
$ ipfs dag get zdpuArZXuXxGBKzsbf9CeMvjpV5ScG1oxwvpmcm7vjZK6JDWB/friends/0/username
"victor"
```

**Comment by diasdavid** [comment]
Examples with js-ipfs -- https://github.com/ipfs/js-ipfs/tree/master/examples/traverse-ipld-graphs

**Comment by guoliu** [comment]
Yes it looks like `dag-cbor` is the way to go. The reason I'm trying to make `dag-pb` work is that it is still the default, making  `dag-cbor` not as convenient in public gateways.

I'll take a look at IPFS discussion forums. Thank you for your response @vmx !
