### ISSUE TITLE
Set up reviewers team

### ISSUE THREAD

**Issue by RangerMauve** [ipld/ipld#193]
Today during the IPLD bi-weekly meeting I brought up that it'd be useful to get a list of reviewers that could be pinged for PRs and the such.

The go-ipld-prime  has had some initial discussions about this here: https://github.com/ipld/go-ipld-prime/issues/370

It'd be good to collaborate on getting a similar process into ipld/ipld.

Ideally, we'd figure out a set of people to ping for reviews that would have act as a sort of "sign off" to get something merged.

- [x] Figure out process for creating teams based on https://github.com/protocol/github-mgmt-template
- [x] Open issue tracking team creation (collab with go-ipld-prime?)
- [x] Identify people to put on team (at least 4?)
- [x] Make the team using the automation flow
- [ ] Test to see if it works

**Comment by BigLep** [comment]
@RangerMauve : are you able to help drive this forward?

**Comment by rvagg** [comment]
We have https://github.com/ipld/github-mgmt/blob/master/github/ipld/team.json now btw, exposing all the aged cruft we've built up in the team list that needs to be sorted. Instead of yak shaving our way through existing teams we could just start with brand new ones.

**Comment by BigLep** [comment]
Agreed on starting with new ones to unblock.

**Comment by RangerMauve** [comment]
Sweet, thank you. I'll get started on reading how this management thing works and make a team for ipld/ipld and maybe ipld/go-ipld-prime to start. 😁

**Comment by RangerMauve** [comment]
Who should be added to the IPLD/IPLD related reviewers?

My gut feeling is @warpfork @rvagg @BigLep and myself to start.

**Comment by vmx** [comment]
Thanks for pinging. I think I don't want to be on the "official" list. But I'm subscribed to the repo anyway and will have a look at most things and will comment accordingly. I just don't want to be obliged due to time constraints. Though, always feel free to add me manually/ping me if you think I should give feedback.

**Comment by RangerMauve** [comment]
> We have https://github.com/ipld/github-mgmt/blob/master/github/ipld/team.json now btw, exposing all the aged cruft we've built up in the team list that needs to be sorted. Instead of yak shaving our way through existing teams we could just start with brand new ones.

Just to confirm, should I be making a fork under my own GH username and doing a PR from there? I currently don't have write access to the repo (assuming this is in purpose since it's effectively admin access to the whole org).

**Comment by RangerMauve** [comment]
Did an initial PR. 😁 Feedback appreciated.

**Comment by rvagg** [comment]
awesome, thanks @RangerMauve

**Comment by BigLep** [comment]
@RangerMauve : I think we're good, right?  If so, let's go ahead and close.  Thanks!

**Comment by RangerMauve** [comment]
Yup! I think I'll add another TODO for myself after this to add docs for how to actually use the reviewers team. Maybe GH issue/pr templates could be useful there?

I think I'll talk about it at the next meeting to get a feel from folks. 😁

**Comment by rvagg** [comment]
@RangerMauve your call on proposing a way forward. I'd be fine with just a README addition but I know some folks like templates for this too.

**Comment by BigLep** [comment]
Good point.  I'll reopen and we close once we have documented.

**Comment by RangerMauve** [comment]
Oh, one weird thing: The @ipld/reviewers group is currently marked as "secret". Did I miss something in the mgmt configuration?

**Comment by RangerMauve** [comment]
Also, looking at the latest "master" branch for [github-mgmt](https://github.com/protocol/design-shop/issues/1388#issuecomment-1102918834), the reviewers didn't get an "id" set. Might be related?

**Comment by rvagg** [comment]
@galargh can you help us on this question ^? What we're wanting is for anyone, regardless of their membership of this org, to be able to ping `@ipld/reveiwers` but I think the "secret" designation might get in the way of that?

**Comment by RangerMauve** [comment]
Ah, you can only @ teams from repositories that the team has added by the looks of it?

**Comment by BigLep** [comment]
That's annoying.  Do you want to open the PR for adding this team to more
repos?  Thanks!

**Comment by RangerMauve** [comment]
@BigLep Added one for ipld/ipld to start.

Are there other teams this should be added to right away?

**Comment by BigLep** [comment]
@RangerMauve : I would add to go-ipld-prime as well.

Thanks!

**Comment by RangerMauve** [comment]
@BigLep Submitted: https://github.com/ipld/github-mgmt/pull/6

Also going to PR to the README for go-ipld-prime

**Comment by BigLep** [comment]
Hi @RangerMauve,

@rvagg is the closest we have to a main maintainer of go-ipld-prime currently.  We have an IPLD triage meeting on 2022-05-03 at 3pm Pacific that could a good time to iron anything out since both of us will be there.  I'll invite you in case it works.

Steve

**Comment by rvagg** [comment]
Yeah, it's pretty much me, with Will helping reviews for now. I think this would be a good addition over there too.

There are a bunch of other repos we could include, but as we move out much further out we tend to get really specific and the list of people who can offer opinions gets even more limited. So let's just start with go-ipld-prime and see how we go.

**Comment by RangerMauve** [comment]
I think this is good to go for now!
