### ISSUE TITLE
Add Captains

### ISSUE THREAD

**Issue by RichardLitt** [ipld/ipld#2]
Like in [multiformats](//github.com/multiformats/multiformats), it makes sense to have captains for each IPLD repo. These captains - also known as leads and project maintainers - would be in charge of their respective repo, making sure that PRs aren't outstanding too long, that issues don't grow stale, and that the code is in good shape. We can add a section to each Readme specifying the captain, and maintain a global list in this README. 

See first mention of this here: https://github.com/ipld/ipld/pull/1#issuecomment-255177655.

**Comment by diasdavid** [comment]
achieved with https://github.com/ipfs/pm/issues/600
