### ISSUE TITLE
Integrate "benefits of content addressing" into docs somewhere (good-first-contribution)

### ISSUE THREAD

**Issue by rvagg** [ipld/ipld#208]
Worked with Chris on a list a while back @ https://github.com/ipld/specs/issues/305

It would be great to find a place to integrate some, or all of this into a doc in this repo (and therefore on ipld.io). I'm not 100% on the whole of the original list so if someone wants to curate it a bit.

I'm also not quite sure where it would go, there may be overlap with existing material that Eric has since added in this repo since we worked on that list.

**Comment by BigLep** [comment]
@RangerMauve : certainly lower priority than other in-flight work, but this is another potential quick win.

**Comment by RangerMauve** [comment]
I could see if it fits in the data model or hello world docs. 🤔

**Comment by BigLep** [comment]
2022-06-14 conversation: @RangerMauve to cull https://github.com/ipld/specs/issues/305 and then put into a new section under https://ipld.io/docs/motivation/.

**Comment by RangerMauve** [comment]
This has been added. 🎉
