### ISSUE TITLE
DAG-CBOR: CID encoding

### ISSUE THREAD

**Issue by burdiyan** [ipld/ipld#209]
According to DAG-CBOR spec IPLD Links (i.e. CIDs) are encoded as `<cbor-tag-42><0-multibase><cid-bytes>`. It's mentioned that for historical reasons CIDs in CBOR must be prefixed with 0.

The type `Cid` in `go-cid` package has a `MarshalBinary` method which outputs just the binary form of the CID without the 0 prefix. This causes problems if you're trying to use other cbor encoding libraries, which can use `binary.Marshaler` interface for encoding, but are failing to add the 0 prefix which makes the encoding incompatible with DAG-CBOR.

My question is: can't the plain binary encoding of CID have the same rules as DAG-CBOR spec? I.e. would this break anything if binary encoding of CIDs were `<0-multibase><cid-version><cid-multicodec><multihash>`? I assume that everywhere CIDs are encoded in plain binary form, they would be using existing DAG-CBOR, so changing `MarshalBinary` method on the `go-cid` package should not break things.

This could also simplify the spec, because this bespoke encoding rule of 0 prefix just for DAG-CBOR makes things harder to understand.

**Comment by rvagg** [comment]
I'm going to close this, I think @vmx has explained the issues here but if you have more to discuss on the topic feel free to continue here @burdiyan
