### ISSUE TITLE
question surrounding go-ipld deprecation notice

### ISSUE THREAD

**Issue by chrisdostert** [ipld/ipld#23]
from Readme: "The Go implementation of IPLD (deprecated)"

Is there a new, un-deprecated repo we should be using instead? Do we need to start one? I might be able to assist w/ surrounding efforts.

**Comment by Kubuxu** [comment]
Where is that written?

**Comment by diasdavid** [comment]
@Kubuxu https://github.com/ipld/ipld#other-repositories

**Comment by lgierth** [comment]
I'm updating the readme in #25

**Comment by diasdavid** [comment]
Thank you @lgierth. Hope this provided the clarity you were looking for @chrisdostert :)
