### ISSUE TITLE
Broken link in 'Kinds' documentation

### ISSUE THREAD

**Issue by CluEleSsUK** [ipld/ipld#255]
The link at the bottom of the kinds page to a specific go file in the go-ipld-prime repo is a 404.

The offending area is [here](https://github.com/ipld/ipld/blob/master/docs/data-model/kinds.md#implementation-references) and the incorrect text is `Kinds in Go: https://github.com/ipld/go-ipld-prime/blob/master/kind.go`.

I searched the go-ipld-prime repo for `kind.go` file in case it had moved and I could raise a PR, but did not see the related file, sorry!

**Comment by RangerMauve** [comment]
Thank you for raising this.

Looking into the go-ipld-prime source, the docs probably probably meant to link to [datamodel/kind.go](https://github.com/ipld/go-ipld-prime/blob/master/datamodel/kind.go) Would you be down to check out some of the other links to see if they need updating and submit a PR from there?

**Comment by CluEleSsUK** [comment]
I tried a bunch of other links (albeit... not the entire docs) and they all worked fine 🥳 
I raised a PR to fix the aforementioned broken one: https://github.com/ipld/ipld/pull/257

**Comment by CluEleSsUK** [comment]
Fixed in #257
