### ISSUE TITLE
[use case] Ethereum Light Client

### ISSUE THREAD

**Issue by hermanjunge** [ipld/ipld#29]
Last Update:  2018.02.21

## Introduction

In Metamask we are working on making the **Ethereum Light Client for Browsers** (and eventually mobile and IoT devices).

**In this write up we discuss the storage problem. Namely, the problem of distributing the ethereum state trie over js-ipfs peers.**

The main idea is to arrive to the spec from here. There will be several iterations involved, my plan is to edit this very write up, mentioning the changes in the comments below.

### Context

* The Ethereum Database consists on a large Patricia Merkle Tree, we are calling `The Trie`. It can be understood as a `state trie`, which root is registered on each `block header` of the `ethereum blockchain`, and its leaves are the `ethereum accounts`. A number of the ethereum accounts carry code on them, these are called `smart contracts`, and the storage code of each contract is stored as well as a trie called the `storage trie`, where the account stores its root.

* Since the trie elements are content addressable, i.e. stored into a key-value database using the hash of their content, we can distribute them in a p2p network of storage: Each peer containing a portion of the whole state, and updating their assigned segment of data on notification.

#### The problem in one sentence

_How can we distribute the ethereum storage data into browser js-ipfs peers updating it efficiently at each blockchain head publishing?_

#### Three areas for working on the MVP

* Obtaining data from _devp2p_
* Bridges
* Peers

##### Features

* Ethereum data is synchronized from `devp2p` and put into a convenient data store (may be a `Redis DB Cluster`.
* For an MVP status, we are interested in (**3 subjects**s)
  * **p2p node discovery**,
  * **block header synchronization**, and 
  * **storage snapshot download**.
* Eventually we will cover transactions, transaction receipts and other.

##### The Future

* **Is important to stress that this must be seen as a "non-ipfs" issue**, i.e. We are designing our system with the assumption we already have this data in some store. At the beginning of this research, We started designing with some focus on simultaneity on both networks. It has proven more useful to separate concerns in order to have a more useful vision with the future (everybody goes to `libp2p`).
* We are counting with the major ethereum clients to eventually incorporate `libp2p` features, facilitating the process of obtention of this data. In other words, while is key to make developments on this area, this step should be seen as an intermediate in the full vision of "_Ethereum on top of libp2p_".

##### Features

Bridges will be deployed with the following **4 features** (**libp2p**, **cache**, **indexes**, **publish**, **respond**)

* **Connected** to the network with `libp2p`.
* Able to **cache** the stored ethereum data as IPLD nodes.
* **Maintaning metadata indexes** to assist the fetching of IPLD nodes
  * A list of examples is displayed below
* Responsible to **publish** when there is a new block head, so peers engage into the updating process.
* **Respond** to specific requests for data.
  * Using IPLD Selectors.
  * Using a different protocol?

##### The Future

* As `libp2p` starts being getting incorporated into ethereum clients, bridges will evolve to "**Hubs**", with similar features to above, only that now, data will be obtained from the very `libp2p` network.
* In any case, in this scenario, a hubs would be seen "a more beefy" peer, as they take more data in than a peer, as well as maintaining and publishing indexes.
* We cannot discard an approach were Ethereum Clients will have the feature of producing these indexes, as the browser light client gains importance in the ecosystem.
* Subscription to published indexes are meant to be opt-in features: Anybody should be able to set up their own. Eventually, the emergence of "**networks of trust**" will define the best indexes to follow (and how an index can lose its reputation if it broadcast the wrong information).

##### Examples of indexes to be maintained by the bridges

* "All the children of the IPLD node `z43AaGF9erQz`" (NOTE: Selector feature could be of use in this problem.
* "The IPLD node for account `0x281055afc` in the block `4,389,678`".
* Mapping of logs to transactions.
* Mapping of transactions to blocks.
* Mapping of ethereum data segment to peer.
* **Variations on the storage** from one block to the immediately former one. We are calling this "**a delta**" (for lack of a better term). This feature is important for peers, as they can build the required nodes list and schedule their download from peers.

#### Peers

Peers are the reason why we are here.

##### Features

The following 5 features will be needed for an MVP (**connect**, **cache**, **subscribe**, **update**, **respond**)

* **Connect** to libp2p.
* **Cache** one or several segment(s) of the Ethereum Snapshot.
  * Using a deterministic approach `peer id` vs `data subset #`.
  * Using a discrete approach and maintaining an index, both in the bridges/hubs as well as distributed over the very peers.
* **Subscribe** to Bridge `Publishing`
  * Most important: `Blockchain head update`. Will trigger updates.
  * Other notifications (ex: new blocks, version updates, etc).
* **Update** the ethereum snapshot segment assigned or chosen by this peer.
  * Using a _delta_ computation, to avoid requesting and traversing from the head(s) of the ethereum snapshot segment(s).
  * May use a metadata index, maintained by a trusted bridge, to quickly determine needed parts.
  * Schedule request of needed parts to peers known for maintaining ethereum data segments (including bridges)
    * To accomplish a behavior not too unlike to torrenting a file.
* **Respond** to specific requests for data whithin the ethereum data segment it is managing.
  * Using IPLD Selectors.
  * Using a custom protocol?

##### The Future

The future goes beyond the MVP. These are some of the features to have

* Transaction broadcast into `libp2p`.
* **Use IPLD Transformations, to perform ethereum state changes over peers having the needed data.**

### A raw list of problems / stuff to hack / trello stickies

Based on the description above. These should be the practical problems to ~hack~ solve (again, this list will be subject to many iterations):

#### The source of data (at least for MVP)

* Get ethereum data from `devp2p` (_good_ devp2p nodes, block header and state snapshot) **as FAST as possible**
  * By all means, "a non-ipfs" issue, but key for everything.
  * Quick and dirty solution: Take `go-ethereum`, and take apart functions of it to build a microservice.
  * Should become a non-issue when clients start incorporating `libp2p` features.
* This data should be stored in the convenient database cluster, as the bridges will be accessing it.

#### Basic Networking (concerning to bridge and peers)

* Create a p2p browser network
  * Who are the signalling servers?
    * Bridges?
    * Dedicated processes?
  * Sending and collecting status data for testing purposes
  * Should we start testing messaging using a custom protocol?

#### Bridges

* go-ipfs nodes
* Connection to the `libp2p` network
  * Will the bridges be connected to the signalling servers?
  * Or, should we expect the peers to connect to bridges?
* Able to read the `devp2p` fetched data from the convenient database setup for the source of data above.
  * Should we import this data into the ipfs datastore of each node?
  * Should we implement a bypass that parses the dag request, and fetches into our `devp2p` store?
    * (as opposed to jsut putting the info into each node datastore)
* Develop the maintaining indexes
  * Need to define which indexes are going to be.
  * **VARIATION INDEX** (or "_delta_"). How do we work a way to tell the peers "These are the variations in your data"?
  * Index `ethereum data subset` to `peer`.
* Able to publish an update of the blockchain head.
* Requests to respond
  * dag requests (ETH IPLD)
  * metadata index requests (should we have a custom protocol here?)
  * IPLD selector requests (when available)

#### Peers

* js-ipfs nodes
* Connection to the `libp2p` network
  * Bootstrap to signalling servers
* Subscribe to `pubsub` topics
  * Blockchain head update
* Maintain an Ethereum Data Segment
  * Deterministic or Discrete TBD
  * First Download comprehends a head, and all their children.
  * Trigger on Blockchain head update
  * Deltas? How do we compute them? Do we get them from the bridges?
  * Schedule and download, using a relative location from the head of the data segment.
* Requests to respond
  * dag requests (ETH IPLD)
  * IPLD selector requests. 

--------------

As stated above, this post is to become the most recent writeup to the solving of this problem, and will pass over a number of iterations. Editions will be mentioned above in the comments.

Special shoutouts to @diasdavid, @dryajov, @kumavis and @whyrusleeping.

**Comment by hermanjunge** [comment]
Adding this, to increase the density of connections in this model https://github.com/MetaMask/mustekala/issues/2

**Comment by hermanjunge** [comment]
So far, three are the "must-have" features to develop in this model:

* Get the synchronized ethereum data from devp2p at all costs,
  * and make the assumption that "is already there", as the method we are using to get it should not affect the construction of the rest of the parts. Which is a good approach if we count with a "ethereum will move to libp2p" future.
* Mount the database you have the eth data into `go-ipfs` client, in order to address it using IPLD.
  * Again, in a eth+ipld future, this component should fade away.

Finally,

* Develop a custom **Content Routing System**,
  * that enable browser peers to hold a shard (or subset) of the ethereum state trie,
  * being able to, on a certain trigger (as a new block publishing),
  * update the contents of their shard based on some diff computed from metadata indexes.

**Comment by yihuang** [comment]
Is it safe to only download state trie from a p2p network without downloading the whole chain and validate it?

**Comment by Stebalien** [comment]
That depends really depends on your threat model and how you got the root of the latest state trie. I believe the idea here is to get the state trie by some trusted mechanism (e.g., use some other consensus system like stellar) and then go from there.

**Comment by hermanjunge** [comment]
@yihuang, @Stebalien is right.

I want to add that each block header contains its **proof of work**, plus a reference to its parent, making financially unfeasible for an attacker to create a fork to the last block you are trusting. As the attacker needs to spend the very processing power as a legit miner, to get you a compliant set of block headers (i.e. that don't fail on _seal verification_).

For example, you can say "I trust that the block 6MM hash is `0xbe847b`", and make sure that you can chain block headers until that point.

Now, you may be in a situation where you were given a fork (i.e. a legit miner o group of miners created via PoW a chain that differs from the consensus of the network starting certain block). In general, what the blockchain clients do is (roughly) looping over your connecting peers and find your **common ancestor** with them, rewinding to that point. In a healthy network, you should be soon working with the **canonical chain**. 

Finally, as @Stebalien pointed, you can always delegate the trust (as it has been mentioned) to another system to do that work for you, delivering to you the right block header.

**Comment by AFDudley** [comment]
Hi Folks, @i-norden, @ramilexe, and others at @vulcanize have picked up and completed much of this work. @eshon and @rvagg this seems to be where the asks from our slack chat came from. I'm not sure what next steps are.
