### ISSUE TITLE
A clarification could be useful in the CARv2 spec 

### ISSUE THREAD

**Issue by John-LittleBearLabs** [ipld/ipld#311]
When "CARv2" is used to refer to a part of the file, it should be followed by a noun that super clearly disambiguates what is meant. 

For example, on [line 86](https://github.com/ipld/ipld/blob/master/specs/transport/car/carv2/index.md?plain=1#L86)
> the CARv2 is a fixed-length sequence of 40 bytes

Should probably read "the CARv2 header is..."

Whereas on [line 89](https://github.com/ipld/ipld/blob/master/specs/transport/car/carv2/index.md?plain=1#L89)
> byte-offset from the beginning of the CARv2 to the first byte of the CARv1 data payload.

Should probably read "... the CARv2 pragma to the..."

I discovered that to be the intention by experimenting with the test fixture. The fact that this term means different things in the same section is confusing.

**Comment by rvagg** [comment]
Indeed, these look like errors, or at least wording requiring clarification; I don't suppose you could work up a quick PR to word them better now you have new-implementer eyes on this? It's always helpful to have someone who comes to these things with fresh eyes.
