### ISSUE TITLE
IPLD Website update call #2

### ISSUE THREAD

**Issue by nicola** [ipld/ipld#4]
Let's try to have an update call early this coming week

Agenda:
- Plan content with Richard
- Updates from @VictorBjelkholm 

Interested: @VictorBjelkholm, @RichardLitt, @nicola

---
Related: https://github.com/ipld/ipld/issues/3

cc @dignifiedquire

**Comment by RichardLitt** [comment]
Hey @nicola - back from vacation. You free early tomorrow (friday)?

**Comment by nicola** [comment]
10pm?

**Comment by VictorBjelkholm** [comment]
I can't tomorrow, busy the entire night...

**Comment by RichardLitt** [comment]
Ahhh I'm sorry, this time won't work for me, actually. Can this be pushed to next Wednesday?

**Comment by nicola** [comment]
Can someone run a poll on doodle for Wednesday?
We really need to meet

(I apparently failed at running the one for the other IPLD meeting)

**Comment by RichardLitt** [comment]
Done. Times in UTC. http://doodle.com/poll/5tsreg7rq75hue22

**Comment by VictorBjelkholm** [comment]
Answered! Seems 4:00 PM UTC works for everyone. Let's do it!

**Comment by RichardLitt** [comment]
Sounds good.

**Comment by RichardLitt** [comment]
Sent out an invite.

**Comment by VictorBjelkholm** [comment]
We had the meeting, was lots of fun. Here are the notes: https://hackmd.io/EYZgbAJgZgLAnBAtAYzADjYmBDYzHYCshATIoXCZdDAOwCM9IQA=
