### ISSUE TITLE
Unixfs v2 discussion?

### ISSUE THREAD

**Issue by mikeal** [ipld/ipld#40]
There's a [discussion noted](https://github.com/ipld/unixfs/issues/1) in the readme but the link shows a 404. This is either because the link is incorrect or the repo is still private. Is there a reason this discussion is still private?

**Comment by schomatis** [comment]
I think it's the link, it should be:

https://github.com/ipfs/unixfs-v2/issues/1

**Comment by Mr0grog** [comment]
Yeah, that definitely seems like a bad link. So far as I’m aware, all the UnixFS discussion has been in [ipfs/unixfs-v2](https://github.com/ipfs/unixfs-v2) (although that repo used to have a different name, it was still in the `ipfs` org). I added links to it a while back in [ipfs/specs](https://github.com/ipfs/specs/tree/master/unixfs), but didn’t know about the link here.
