### ISSUE TITLE
IPLD Redux (Scope, Definitions and Dependencies)

### ISSUE THREAD

**Issue by mikeal** [ipld/ipld#50]
After a long and productive sit down with @Stebalien and @jbenet we figured out a workable path forward for IPLD.

Some of the prior terms have been reduced in scope and some of the previous "IPLD Next" work has been pushed out to the future. The biggest changes:

* The advanced type system we've been talking about is being pushed into the future and is not part of any of the definitions below. We expect the world to look very different once we have WebAssembly accessible and available in IPLD and the potential benefits and changes to this advanced type system are big enough that it's best to just wait to build it until we can rely on WebAssembly.
* We are punting on generic transcoding between codecs. If you want to turn a `dag-json` object into a `dag-cbor` object you'll need to write code specific to translating between those codecs. The prior "canonical JSON" threads are being closed out and punted.
* "IPLD Paths" needs to be its own spec. Defining how escaping works is going to be painful :(
* The "IPLD Data Model v1" **DOES NOT** describe existing formats like `git` and `dag-pb`. The "IPLD Data Model v1" is strictly for new codecs like `dag-cbor` and `dag-json` to *support* and for complex data-structure specifications like HAMT and ordered indexes to *depend on*. 
   * A key result of re-scoping the data model to new codecs is that we can require a broader set of basic types. This raises the bar for implementing a codec that *supports* the data model (`dag-json` has to figure out how to represent 64bit integers, Binary, etc) and it gives a much better foundation for complex data-structure specifications to be able to build and rely upon.
  * While this raises the bar for implementing a codec that supports the data model it reduces the requirements on implementing a codec that does not. A codec only really has to have a conceptual understanding of a link and be able to represent it as a `CID`, and understand the Path spec. Since replication is built strictly from codecs and blocks this also makes writing replicators easier **and** broadens the nodes that are easily replicated even with more advanced graph syncing.

```
       IPLD Dependency Graph

+---+                          +-----+        +---+
|CID+-----------+-------------->Block+-------->Raw|
+---+           |              +--+--+        +---+
         +------v-------------+   |
+----+   |Links (Conceptually)|   |
|Path|   +------+-------------+   |             +-----------+
+-+--+          |                 +------------->Replication|
  |    Codecs   |                 |             +-----------+
+-v-------------v-----------------+---+
|                                     |
| +---+    +-----------------------+  | Complex Data-Structures
| |Git|    |     Data Model v1     |  | +--------------v-------+
| +---+    |                       |  | |                      |
|          | +--------+ +--------+ +----> +----+ +-----------+ |
| +------+ | |dag|json| |dag|cbor| |  | | |HAMT| |Sorted Tree| |
| |dag|pb| | +--------+ +--------+ |  | | +--+-+ +----+------+ |
| +------+ |                       |  | |    |        |        |
|          +-----------------------+  | +----------------------+
|                                     |      |        |
+-------------------------------------+      |        |
                                             |        |
                +----------------------+     |        |
                | File System (unixfs) <-----+        |
                +----------------------+              |
                +--------------------+                |
                |                    |                |
Structured Data | VR, Geo, SQL, etc. <----------------+
  w/ indexes    |                    |
                +--------------------+
```

While our dependency chain isn't laid out in a perfect layering system it does show how powerful the separations are when you think about things from the point of view of a consumer of each component.

* Structured data people use in applications and file system representations rely on some generic complex data-structures. Because those are built on the Data Model they work with *any* codec that implements the data model, they aren't locked into `dag-cbor` and can mix and match different dag implementations without re-implementing the data-structures or transcoding the nodes. This means a file system in `unixfs-v2` could have sub-directories that are still `unixfs-v2` but are encoded using entirely different codecs.
* All of these advanced data-structures **and** existing content addressed data like `git` conform to the same codec interface which means the graphs can all be easily replicated and linked to each other.

### Future (Currently out of scope)

For the purposes of the above dependency graph and for the next quarter or so the following work is considered out of scope. However, I would like to capture some of the key things we've talked about.

* Mutability
  * We eventually need a "mutable link." @mikeal thinks this should be much more generic than just a public key that points to a root node, we should support different log formats that, in addition to the latest root, have a notion of history.
* Paths **in** Links. 
  * The current Link Type in the data model is strictly a CID, it does not include a Path. This may be added in a future version of the Link Type but we're punting for now.
  * Similarly, "conceptual links" for the purpose of codecs that don't support the data model are strictly CIDs.
* Higher level paths
  * The current IPLD Path spec will operate below the layer that `HAMT` and other sharded data-structures operate. In the future we'll need a higher level solution, especially once we have mutable links and paths in those links because we can't guarantee that the low level path will remain the same between mutations of sharded data-structures.
  * There's not alignment as to whether or not this needs to be a new scheme or not.
  * If we wait for WebAssembly, and the next iteration of a Data Model, we can load the implementation for a sharded data-structure at its root node. This would future-proof high level paths to any future data-structure.
  * This does **not** effect `ipfs://` paths into MFS, the spec for `unixfs-v2` should include an extension to the Path spec for any sharded data-structure it supports (currently just hamt).
    * Yes, this means that if we want to add a sharded data-structure to unixfs we'll need to release a new version of the spec but in this pre-WebAssembly world we need to do that anyway to ensure compatibility between implementations.

**Comment by Stebalien** [comment]
Excellent write-up!

**Comment by vmx** [comment]
Question about the "IPLD Dependency Graph". Do the arrows (e.g. `xx --> yy`) mean `xx` enables us having `yy`? If yes, then there should be an arrow from `Raw` to `Block` and not the other way round.

I don't understand what "Sorted Index" means. Is it a layer on top of IPLD where you can insert things, let's say my book collection. I can define that I want an index that can return me a list of all books sorted by author? That index would directly be stored in IPLD and not somewhere externally. I think of it as a View in Apache CouchDB.

In the diagrams the "Sorted Index" should be renamed to just "Index", or "Index" should be a separate category as e.g. for spatial data the index normally isn't a sorted one.

**Comment by mikeal** [comment]
> Do the arrows (e.g. xx --> yy) mean xx enables us having yy?

Yes. However, by "Raw" I actually meant "Raw Block" :) 

I only wanted to show that there is one thing you can use the Block interface for that does not require a codec implementation.

> I don't understand what "Sorted Index" means. Is it a layer on top of IPLD where you can insert things, let's say my book collection. I can define that I want an index that can return me a list of all books sorted by author?

In the same way that a generic `hamt` data-structure allows us to shard a single address space over many Blocks the "sorted index" would allow us to shard a single address space over many Block and maintain some sort of useful ordering. Effectively, we're talking about some kind of efficiently sharded tree structure that maintains key ordering (hamt does not).

We are not referring to a foreign index in some other system. "Index" may not be the right word, this isn't a secondary index, it's a data-structure for storing things by a primary key efficiently over many blocks with some kind of range request interface.

The index could be a spatial index, but the key difference, I think, between what you are talking about and what I'm talking about are that the index is not a secondary view of primary data, it's the primary way people will lookup and replicate data and so you need to be able to replicate specific ranges of the data.

**Comment by vmx** [comment]
> We are not referring to a foreign index in some other system. "Index" may not be the right word, this isn't a secondary index, it's a data-structure for storing things by a primary key efficiently over many blocks with some kind of range request interface.

That's how I understand it. So it's a layer on top of IPLD which processing things and stores them again in IPLD, without any secondary indexing. So you have to use that higher level layer again to get the data out as the actual stored data in IPLD might not resemble what you've put in.



> The index could be a spatial index

So I guess my nitpick is to just not combine the word "sorted" with "spatial" or "geo" :)

**Comment by mikeal** [comment]
> So I guess my nitpick is to just not combine the word "sorted" with "spatial" or "geo" :)

Ya, @jbenet already suggested we use the term "collection" for all of this (including hamt). 

We could define collection as "single namespace sharded over many blocks." Then we can distinguish between them as "Unordered Collection" (hamt) and "Ordered Collection" and in the future "Geo-Spatial Collection" could also be a thing.

**Comment by mikeal** [comment]
wouldn't VR data just be in a normal spatial collection?

**Comment by vmx** [comment]
Yes, VR would be a spatial collection.

**Comment by warpfork** [comment]
Do we have any discussion yet on some of the nitty-gritty details of what is and is not acceptable value types and ranges for the data model -- e.g. in dag-json and dag-cbor -- such as:

- map key types: strings?  are ints allowed?  what range -- int32; uint64; etc?
- numeric out of bounds: is an implementation free to error on "too large" numbers?  will there be minimum required supported ranges?

**Comment by mikeal** [comment]
> Do we have any discussion yet on some of the nitty-gritty details of what is and is not acceptable value types and ranges for the data model -- e.g. in dag-json and dag-cbor -- such as:

Sort of. We have a list of "required types" we are defining for the "IPLD Data Model." Draft of that spec is here https://github.com/ipld/specs/pull/72/files#diff-a46712f91d2026a53f1379b3561df3f8

**Comment by mikeal** [comment]
Closing. This issue was mostly to message what is happening, we have the specs PR to track the bulk of the changes.
