### ISSUE TITLE
Dead link to multicodec-packed

### ISSUE THREAD

**Issue by lgierth** [ipld/ipld#6]
Its target was removed here: https://github.com/multiformats/multicodec/pull/16

**Comment by RichardLitt** [comment]
I'm not sure where the big rename left us in terms of repos. @diasdavid Can you explain it briefly? Where should multicodec-packed point now?

**Comment by RichardLitt** [comment]
@lgierth Where is the dead link?

**Comment by diasdavid** [comment]
@vmx fixed this :)
