### ISSUE TITLE
Libp2p and IPLD in TCP/IP stack

### ISSUE THREAD

**Issue by IR-Consensus** [ipld/ipld#60]
Hi
I want to implement mechanisms Decentralized on Internet (tcp/ip), 
But I have a question?
Can I  do it  with better instructure on  internet?
my goal use of instructure (libp2p-IPLD) in network stack,But I see that for routing packets in internet need to Add headings to packets for find the path  to destination.
Are governments able to filter and restrict Internet users? (becuase for routing need to ip address in  routers).

**Comment by vmx** [comment]
Please ask these kind of questions on the discussion forum at https://discuss.ipfs.io/.
