### ISSUE TITLE
Add implementations list

### ISSUE THREAD

**Issue by RichardLitt** [ipld/ipld#7]
There should be a list of current and planned implementations. See https://github.com/ipld/website/issues/16. 

Will open a PR when that issue is resolved. 

depends on ipld/website#16

**Comment by diasdavid** [comment]
On the readme :) https://github.com/ipld/ipld#repositories

**Comment by RichardLitt** [comment]
@diasdavid Thanks, but that's not quite what I was going for. That list of repositories also has things like website and spec in it. I really want a separate sections for implementations. See #11.

**Comment by diasdavid** [comment]
@RichardLitt understood, let's keep the conversation in the PR #11 to avoid confusion, thank you.
