### ISSUE TITLE
IPLD Open House - May 16th, Berlin, Germany

### ISSUE THREAD

**Issue by mikeal** [ipld/ipld#71]
# Notice! We are breaking for some food 13:45, DM @mikeal on twitter if you want to join us.

Are you in (or can you get to) Berlin? Do you love IPLD and the promise of content-addressable data structures?  Let's hang out!

We’re inviting folks that are in Berlin to come and chat about IPLD the day before the Data Terra Nemo Conference.

* Day/Time: May 16th, noon - 5pm.
* Address: Design Offices: Unter den Linden 26-30, 10117 Berlin, Germany

We figure this will be a small, cozy event.  Anyone interested in IPLD can come by and chat with the team. We may do a few talks, we may not, it depends on what people are interested in.  Likely topics of chat include IPLD Data Models, Schemas developments, UnixFSv2 design, and canonicalization of all kinds; and especially, applications that YOU can think of where IPLD would make life cooler and better.

Light lunch provided on site; dinner follows!  Optionally, maybe some sort of drift around evening venues with beverages.  Come say hi!

**Comment by warpfork** [comment]
> applications that YOU can think of where IPLD would make life cooler and better.

This dude has two thumbs and is also e x t r e m e l y likely to talk about package managers and reproducible builds, on that note, if anyone is interested in such topics :)

**Comment by vmx** [comment]
CC'ing a few folks that might be interested @rklaehn @almereyda @tomaka

**Comment by warpfork** [comment]
also @oed

**Comment by mikeal** [comment]
maybe @janl, @rmehner, or @boennemann are interested.

**Comment by mikeal** [comment]
oh, and @felixge :)

**Comment by mikeal** [comment]
> How about @seidtgeist though?

Definitely, it’s open to anyone who can make it :)

**Comment by felixge** [comment]
I'd love to join, but unfortunately I'll be in Moscow that week :(

**Comment by seidtgeist** [comment]
I can’t make it, wish you a great time. Thank you for thinking of me, other Stephan ❤️!

**Comment by yoshuawuyts** [comment]
Maybe I'll drop by! -- it coincides with the Dat hack week, so will have to see. But there's not many reasons why I couldn't make it (:

**Comment by mikeal** [comment]
Notice! We are breaking for some food 13:45, DM @mikeal on twitter if you want to join us.

**Comment by rmehner** [comment]
@mikeal hope you had a good event, I'm sick in bed and couldn't join :/ Are you around for the conferences?

**Comment by mikeal** [comment]
@rmehner I’m here for DTN this weekend but nothing after :(
