### ISSUE TITLE
Does any implementor of ipld have to understand every codec?

### ISSUE THREAD

**Issue by tysonzero** [ipld/ipld#91]
As far as I can tell the only way to see what cids are referenced by a block is to parse it into the ipld data model based on the codec given. Presumably this means that a lot of applications using ipld will have to understand every codec, as otherwise things like recursive pinning and such won't work if any item in the dag contains an unrecognized codec.

This is as opposed to regular files and folders where you can transmit and safely store something like:

```
index.html
static/
  script.js
  style.css
```

whilst the storer doesn't need to understand `html`, `js` or `css`.

From my understanding the reason for this decision was to improve interoperability with existing Merkle dags, where requiring them to use a standardized "file/folder" Merkle dag format would require re-hashing everything.

I mostly just want to make sure I understand the situation correctly, so this is not really a bug report or feature request or anything like that.

**Comment by rvagg** [comment]
Yes, that's correct, you have to know how to parse out "links" from formats to know how to follow them. Most graphs use only one or two codecs (e.g. dag-pb + raw, or just dag-cbor, or the set of bitcoin-* codecs) so it tends not to be a big problem in practice. But if one were building a very generic pinning service then you'd be wanting to pull in as many codecs as possible or you'll have to treat opaque blocks as terminals. But comprehensiveness is probably a bit of an unreasonable goal. Imagine linking from dag-pb to into Ethereum blocks which in turn link out to some other format. At some point you have to draw a line and say you're not "pinning" certain types of blocks (a pinning service probably doesn't want to navigate into Ethereum blocks for example).

If we're focused on IPFS, I think you'd get 99% coverage if you had dag-pb, raw and dag-cbor. Add in dag-json for a little more, and that's probably enough. Some formats that you might find in there, like cbor and json, don't even have links that would convert to CIDs in the data model, so you don't need to parse them, just treat them as terminals.

Does that help?

**Comment by tysonzero** [comment]
That helps a lot thanks!

Presumably in cases where the existing hashes are of incredibly large blocks, this flexibility will not save you, as there is no hash-preserving way to convert a file into a list of chunk hashes? Although in practice this seems like it should be rare, as existing Merkel trees seem to generally have reasonable block sizes.

Hypothetically if someone were designing a new Merkel tree today, such as for a blockchain, would it be reasonable in most cases to simply use `dag-cbor` instead of creating a new codec?

I now see how you can implement a wide variety of implementations while only caring about a few codecs. As you can simply treat a cid with an unknown codec similar to how you’d treat a cid with a manually crafted hash that will never match anything.

**Comment by rvagg** [comment]
Well, there are plenty of ways to chunk up a file into multiple blocks, and you can use the `raw` codec for plain files to do that. That's how UnixFS in IPFS works, it will mix metadata in dag-pb with raw blocks chunked into pieces, each hashed.

@ribasushi is one of our resident expert in chunking algorithms if you want to go further into that topic, there's a deep science in being able to reliably and predictably slice up files into ways that minimse duplication and preserve the repeatability of hashes.

On the topic of large files, this is a recent and interesting discussion that Adin has been pursuing @ https://hackmd.io/@adin/sha256-dag that pushes the limits of IPLD a bit too far (at the moment) but explores the problem of large existing files that don't fit into our smaller-chunk universe and how we might address them. We also have a spec for a "flexible byte layout" @ https://github.com/ipld/specs/blob/master/data-structures/flexible-byte-layout.md which is intended to serve as a byte format for UnixFSv2 if we get there but is also generically useful. The nice thing about defining it this way is that it's codec agnostic. It can span dag-cbor, dag-json, raw and a possibly other codecs. It's the layout that matters. At the moment we'd probably implement it with dag-cbor if we were to push a UnixFSv2 out today (IMO). But Mikeal has also been experimenting with new possible formats that handle content addressed data in more consistent, stable and safe ways. https://github.com/mikeal/zdag/ and https://github.com/mikeal/simple-dag/.

wrt implementing a blockchain today. If I were doing that then I'd reach for IPLD as a way to abstract the data coding layer away. Most blockchains today care too deeply about their data encoding formats and it takes up large chunks of their codebases. IPLD is trying to offer a way to take away that concern. Filecoin is really the first to do this. It's all dag-cbor, and their CIDs are all `dag-cbor`. That's best practice today IMO. Hopefully we'll get better options than dag-cbor in the future.

I hope this is all interesting and relevant for you!

**Comment by tysonzero** [comment]
Thanks for all the information!

My one additional question would be if there is any plan to utilize multicodecs for things like setting desired HTTP Headers alongside uploaded files, for gateways to use. I know there are a variety of discussions going on around solving this problem, currently leaning towards using a manifest file.

**Comment by rvagg** [comment]
I'm not sure about the multicodecs<>http headers question. Those discussions were probably before my time. I'm aware that there's lingering questions about whether we should just import mime types into the multicodecs table to enable more broad use, but beyond that :shrug:. It might be a question for gateway implementations rather than a general spec question I think.

**Comment by tysonzero** [comment]
Gotcha. Thanks for all the information!
