### ISSUE TITLE
Consolidating IPLD documentation

### ISSUE THREAD

**Issue by warpfork** [ipld/ipld#93]
I'd like to discuss moving a large amount of our docs and reference material to one, consolidated repo.

There are several reasons for this:

1. It's preferable to only do the tooling wrangling **once**.
2. Separate repositories require creators of any PRs or issues to figure out _which_ repo to target _before_ the communication is initiated.  This is a barrier to initiating communicate.  It also often results in the infamous "please reopen your issue in another ~castle~ repository" dance, which is typically discouraging to contributors (both new and recurring).
    - I ironically experienced this trying to decide where to open this issue, which delayed it for some time :)
3. It's currently impossible to track document _moves_ when they cross repos.  Things get lost.
    - This comes up somewhat recurringly.  Documents have already moved back and forth between the "docs" and "specs" repos several times since the former's initiation, and in the process, it's become such a worry that any changes will be made to the "wrong" divergence that it discourages contribution or fixes.
4. _it is not possible to do link coherency checks_ as a part of a CI process, because we link heavily between different categories (e.g. docs amd specs) that are currently in different repos.
    - ^ this is the "game, set, and match" concern for me.  We **need** this kind of link checking.  Without it, we're worse off than an unmaintained wiki -- we can't even _see_ our redlink problems (which makes improving them very difficult).
5. I notice the IPFS project teams, in their work on docs and with focused contributors on docs, is [moving to a consolidated repo](https://github.com/ipfs/ipfs-docs/projects/3) -- presumably for many of these same practical reasons -- and while we don't have to be on the same page, I think it maybe doesn't _hurt_, either :)
    - n.b. I am not suggesting we consolidate together with the IPFS docs.  That would be a stride too far towards the noisy at this time.  Just that one consolidation for each of {IPFS, IPLD} makes quite a bit of sense to me.

In fairness, I will also note known dissents:

- Having separate repos may make it easier to have clear policies about what contribution quality levels, and contribution constraints, are considered appropriate.
    - (My counterargument is: we don't actually do this right now (certainly not in a codified mandatory-access-control way); and so I don't see why we couldn't do this by policy and review process, at root directory granularity, even in a shared repo.)
- It is somewhat disconcerting to readers on GitHub to encounter a bunch of content that needs preprocessing in order to become a website, rather than being directly readable on GitHub.
    - (I commiserate with this for sure!  But I think we can find a way to make this work.)
- Having different issues buckets for e.g. specs vs docs is constructive because they require different levels of engagement.
    - (Perhaps true.  But looking across issues we have in ipld/ipld vs ipld/specs vs ipld/docs right now, I don't think there's much evidence that trying to separate these a-priori really... works.  And very frequently, a single issue touches needs that, during discussion, are evolved into requests of _both_ formal specs, and the more reader-friendly documentation that should be coupled (!) with them.  And are we sure we can't do this with tagging mechanisms instead?)

Here's my proposal:

- We select the list of repos to converge -- I propose ipld/ipld, ipld/website, ipld/specs, and ipld/docs
    - Some of these are relatively "old" and already somewhat legacy already, but, I still feel including them in unified history could be useful for reference (and also to pluck through and make sure we didn't miss any important content from them which hasn't been replicated in the newer repos yet).
- We create a new repo, and make one very large merge-and-move commit, which results in all those repo's contents being in a "./_legacy/{reponame}" dir in the new repo.
    - all the old repo commits are still in history -- same commit hash
- We implement the essential site build&deploy infra (once!), complete with link checker (!!).
    - this is awfully close to what we already have in the more recent repos.  But needs some tuning.
- I would promise to then wield executive function intensely (and prioritize the heck out of working on this) until all content is moved into new positions, and "./_legacy/" is emptied.
    - This may take a week.  Or two.  But I will promise, once we begin, to not to let it drag out (because I know how much that would suck for everyone _else's_ ability to work on docs for the duration).
    - I would not be using PRs for this because it will not move fast enough and it would not get done. We can discuss some things about directory layout up front, but once the moving begins, someone just has to cut through all the weeds and Do The Thing.  We can re-argue topology and additional document moves in subsequent rounds.  I'm just promising to get everything "close", and ready for further iteration.
    - I suspect our top level directories will be "docs/", "specs/", "libraries/", and "tools/".  (There may be a smattering of others, e.g. perhaps "media/".  Let's not get too hung up on the details, in this issue.)

Why now?

- I want to write new docs, and right now, I feel the barriers are too huge.  I can't be confident that my links work.  I don't feel confident I'm contributing to the right fork of e.g. the schema docs (yes, even though I wrote them in the first place).  But I can't sit around not writing new docs indefinitely, waiting for these issues to be magically resolved.  So, I want to have this discussion.
- We have technical work to do on the publication process.  There are lot of tooling around VuePress and smoothly publishing to IPFS that done by other teams that we should replicate for our stuff.  I want to do this once, not 2 or 3 times.
- We have technical work to do to get link checker tools set up in CI.  Again, I want to do this once, not 2 or 3 times.
- We are currently missing a nice, visually pleasing landing page, which can do good routing of readers to the various more detailed content we have.  We need to do the development work to have that again, and when we do, it should definitely be integrated with our link checkers, and also I don't see why it shouldn't use the same deployment pipeline as the rest of our content.
- None of this gets easier by putting it off.

There's a couple of details we can debate in advance.  But mostly I'm opening this issue to discuss and look for consent on the single big issue: Can we move to a consolidated repo for this content?

**Comment by mvdan** [comment]
I'm always going to support joining many closely-tied repositories into a single one. I fully agree that the ipld, website, specsc, and docs repos don't really need to be separate. When I first was going through the content, it was confusing what qualified as specs vs docs, for example. It was also hard to tell what should be the "landing README" for all of IPLD on GitHub, as there were easily three possible answers to that.

**Comment by johnnymatthews** [comment]
Even though I'm not particularly tied to this project, I'm a huge fan of consolidating docs.

> It is somewhat disconcerting to readers on GitHub to encounter a bunch of content that needs preprocessing in order to become a website, rather than being directly readable on GitHub.  - @warpfork 

I've run into this problem in the past. Here's a solution I've done at previous projects:

1. Put docs, images, videos, and any other content into a repo called `ipld/docs`. 
2. Create another repo called `ipld/docs-site` containing all the fancy site-building Hugo/VuePress/Jekyll stuff.
3. Add `ipld/docs` as a sub-module into `ipld/docs-site`.
4. Have the `ipfs/docs-site` build whenever there are changes to either repo.

> I would promise to then wield executive function intensely (and prioritize the heck out of working on this) until all content is moved into new positions, and "./_legacy/" is emptied. [...] This may take a week. Or two. - @warpfork

It's probably gonna be closer to two than it is to one.

Again, I'm a big fan of this move! Happy to help out and give pointers if you need a hand.

**Comment by warpfork** [comment]
> directly readable on github

I think the main issue I've had with this is that the more the content uses features of the static site templating system, the more it becomes illegible on github.

If this happens in the deeper directories of content... it's probably fine.

But if it's not possible to have at least one README-worth of landing content that's legible and not-weird-looking on GitHub, it's kinda troublesome.  Just enough to say "hey this is the website repo!  go to the website to view it nicely!" is fine, even -- but that document really has have room to be.

I think this is probably possible just by using a directory structure intelligently.  But I will admit, I poked at VuePress a bit and found it pretty unconfigurable on a few key things.  So it does look like if I want a main README on GitHub that's not included in the site, the whole site has to be at least one directory in from the root dir of the repo, yep.

(FWIW, I tend to be a submodule fanboi.  But it seems probably a little overkill here.)

> It's probably gonna be closer to two than it is to one.

*polite cough* yeah

> Happy to help out and give pointers if you need a hand.

Big less-than-three!

**Comment by mikeal** [comment]
* ipld/ipld - we can deprecate this repo today
* ipld/website - we can deprecate this repo today, the website is now just a forward to /docs
* ipld/specs and ipld/docs
  * We have outstanding links to specs.ipld.io and docs.ipld.io now, so factor in that there’s a cost to this migration. Still may be worth it, but let’s factor it in.
  * There’s a very different user journey these sites currently provide. Converging them will require some design work to facilitate both because they really are for different audiences. It’s not impossible but it’s also not trivial.

I think we can take aggressive action on deprecating /ipld and /website but we’ll need to talk a bit more about docs and specs.

We should also consider more aggressive consolidation if we’re starting down this path anyway. Multiformats needs better docs and has marginal docs spread across IPLD and IPFS which both rely up on them. It might be worth just integrating all of the documentation and specifications of the protocol stack.

**Comment by vmx** [comment]
> * ipld/specs and ipld/docs

If I understand @warpfork correctly the point is not to mix docs and specs into a single thing. It's just about the repository organization on a source level. So there could still be a `spec` and a `docs` directory,which then gets deployed to their corresponding sub-domains.

**Comment by warpfork** [comment]
To make a public status update:

I'm slowly (but surely) working on this.

As the person currently holding the title of "Steward" for IPLD, it seems to be both my responsibility for collecting feedback about the current state of our documentation, and for collating and resolving any problems with it.  I've continuing to collect a lot of feedback that the current state of our documentation is rough, and so I continue to be committed to taking actions on it.

I've assembled most of the technological schlep that I want for this.  The theming will be very similar to the current.  It will remain mobile friendly in the same way as the current docs product.  I'll be using a system that allows much more explicit control of the nav menu, because I believe that will be important for the amount of information that we need to gather and (well) navigate.  I've mapped out how to do redirects for any old links that are especially highly referenced.  I've also assembled the link checking tooling to make sure that every single internal cross-link is checked at all times, including links to section IDs within pages, so we have drastically fewer broken internal links in the future.  I'm very happy about all this and believe it will significantly increase the maintainability of the repo.

(It's not technically relevant, but, Mikeal, you may be amused to know: a bunch of the technology I'm pulling together was triggered by a recommendation from your friend Blake.  Successful small-world'ing!)

One piece of technology I have not pre-wrangled is the final publication step (the yeeting of the fully-baked html content into somewhere it is accessible online).  I think I have heard several new technology options (including content-addressed backend ones which may make us especially happy) have appeared lately, but haven't surveyed them.  If anyone's got that knowledge in their head, pointer appreciated.  Otherwise I'll wrangle that at the end.

It's now coming up on time to start moving stuff.

In this process, please be advised that I am going to have a limited "spoons" budget.  My highest priority, overridingly, is to reach an end state where the result feels consistently and sanely navigable to me.  I will review this with other readers (and especially, those who are *not* already familiar with this content -- meaning almost no one in this issue :) I love you, all the same, but fresh eyes matter).  A secondary priority will be maintaining current links.  A (far, far) tertiary priority will be keeping any currently open PRs easily mergable.  **I do expect the primary priority to regularly override the secondary priority and the tertiary priority**.  This is going to be a large amount of work; the non-primary goals are going to get a "best effort"; and ultimately, I'm a lot more worried about improving the experience of {every future reader} than maintaining the experience of {the small number of current readers}.

My current plan is:

- as described earlier, do several big merges of content from the existing repos; move them into a `_legacy` dir; and then gradually, in many commits, I will carefully port forward content, while updating it and cross-linking it, and continuously validating all links in new content actually land somewhere.
    - Yes, I will keep the `docs/` and `specs/` distinctions separate, as directories, and in the navigation.  They will just be heavily cross-linked.
    - The edit history (git-blame, etc) should largely survive this!
    - I am also going to write *new* content, on demand, as I do this.  "Strike while the iron is hot" reasoning.  Any time that porting forward old content demands connective tissues, I'm going to write it.
- Publish new content demo under a temp URL.  Begin inviting readers to review.
- When ready, publish the new content under the `ipld.io` URL.
- **Begin to mark all but one of these old repos as 'archived', in github.**
    - I do not want to keep getting new PRs and issues onto the fractured old content after I start moving and fixing all of its crosslinking, so, the earlier this can be done, the happier I'll be, and the fewer contributors we may accidentally mislead into doing badly-placed work.
- I think it may be reasonable to move some repos, for github redirect purposes -- but we can discuss this:
    - I might propose `ipld/ipld` to `ipld/ipld-legacy` (then archive it);
    - and move `ipld/specs` to `ipld/ipld` (because I think at this point, we have more links pointing to the specs repo than other places, and those links are more recent / higher relevance / etc than most other links which lead elsewhere but may be from older strata of history, so I think having the github redirects on those might be the most relevant).
    - Ultimately, though, I don't have strong feelings about it -- this is window dressing that's relevant to {past} readers, and I'm more worried about {future} readers.

I am going to hope to make the new unified content, and thereafter more and more new docs, available very soon.  My goal is within a week or so.  (If you've been getting notifications from me chasing PRs to land... this is why!)  (There is a motive force here: there are other initiatives in Protocol Labs taking off which have indicated that IPLD docs are a serious sticking point for them, and have their own timelines on which they want to see new work moving, and so I'm very much wanting to get them unstuck as consumers!)  I'll continue to post updates as drafts become available.

**Comment by warpfork** [comment]
Closing as done.
